# Generated by Django 2.0.6 on 2018-08-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180828_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], max_length=25),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
